### PR TITLE
Adds userDetailsService() to builder

### PR DESCRIPTION
**Pull request by ttomsu**
cc @rwinch

### CODE REVIEW

**Comment by jadekler** [comment]
@ttomsu why the maven publishing plugin? The rest LGTM

**Comment by markthemarkest** [comment]
LGTM to me as well. I'm also curious about the maven plugin.

**Comment by ttomsu** [comment]
I was using it to `publishToMavenLocal` so that my other project could use and test it:

https://github.com/ttomsu/gate/blob/google-oauth-saml-dsl/gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy#L104

I made a couple of local edits to assign a bogus version and groupId to get it working. I'd love to learn how to pull it in using just gradle.

**Comment by jadekler** [comment]
@ttomsu Could you edit this commit to remove the gradle changes? Once that's done we're happy to accept this. 

The tentative plan for people using this is hosting it on spring.io, which should allow people to import it as any other spring dependency.

**Comment by ttomsu** [comment]
Done.

**Comment by jadekler** [comment]
Thank you for the contribution!

**Pull request merged**
